# Generated by Django 4.0.4 on 2022-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=60)),
                ('Title', models.CharField(default='', max_length=70)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Date', models.DateField()),
                ('Image', models.FileField(max_length=254, upload_to='uploads/images/')),
                ('File', models.FileField(max_length=254, upload_to='uploads/files/')),
            ],
        ),
    ]
