# Generated by Django 4.0.4 on 2022-04-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='File',
            field=models.FileField(max_length=254, upload_to='media/myFiles/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Image',
            field=models.FileField(max_length=254, upload_to='media/myImages/'),
        ),
    ]
