# Generated by Django 4.0.4 on 2022-05-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_alter_certificate_file_alter_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='File',
            new_name='myFile',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='Image',
            new_name='myImage',
        ),
    ]
