# Generated by Django 4.0.4 on 2022-05-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0003_rename_file_certificate_myfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='myImage',
            field=models.ImageField(max_length=254, upload_to='media/myImages/'),
        ),
    ]
